name: Bump Verifast

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: macos-14
    steps:
      - name: Run bump-formulae
        uses: Homebrew/actions/bump-formulae@v4
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN != '' && secrets.HOMEBREW_GITHUB_API_TOKEN || secrets.GITHUB_TOKEN }}
          formulae: verifast
